import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App Router",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex justify-between items-center">
          <Link href={"https://flowbite.com"}>
            <Image
              src={"https://codemobiles.com/biz/images/codemobiles_logo.svg"}
              width={200}
              height={100}
              alt="Logo"
            />
          </Link>
          <span>NextJs AppRouter BB</span>
        </nav>
        <div className="container mx-auto my-4">{children}</div>
      </body>
    </html>
  );
}
